Fix macos keys
magmax/python-readchar pull request #89
Opened 2022-07-31 15:26 UTC by fleytman

After merge https://github.com/magmax/python-readchar/pull/79 in macos was broken enter. It's fix.

And i include https://github.com/magmax/python-readchar/pull/70

2022-07-31 15:55 UTC, Cube707 requested changes
First of all, thanks for contributing, but your PR is not well formated.

Please keep your commits atomic (meaning each one should containe a single standalone change), so avoid commit that just fix a small mistake in a previos commit (like your last commit that just adds a missing `\n`). Please create a first commit for your refractoring of the `if` statements and than a second commit with your macos-fix.

Also your commit messages contain some random text. keep the first line short and descriptive and use the second line to give further explanations if necessary ([see herer for more info](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)). And only link other issues / PR's on commits that specifically fix them, not when the fix is mixed with other stuff.

-----

Please remove #70 from this PR. I will take care of it once I have some time for it, but it is to complex and I don't know enought about macos to just handle it quick and dirty. For now this will have to stay a limitation (which is fine as MacOS is not supported anyway)

2022-07-31 15:55 UTC, Cube707 commented on readchar/__init__.py
> +if platform.startswith(("linux", "darwin", "freebsd")):
thats a cool idea. very nice.

2022-07-31 15:55 UTC, Cube707 commented on readchar/_macos_key.py
> +
please import exsiting definitions from other files here
```suggestion
from ._posix_key import *
```

2022-07-31 15:55 UTC, Cube707 commented on readchar/_macos_key.py
> +CR = "\x0d"
this is alread defined. no need to redefine it

2022-07-31 15:55 UTC, Cube707 commented on readchar/_posix_read.py
> +            ch = sys.stdin.read(1)
this is defnetly to complex for me to just sign of on. Please remove #70 from this PR. I will decide if it makes sense to include it once I finde the time to get around to it.

2022-07-31 15:55 UTC, Cube707 commented on readchar/key.py
> +    from ._posix_key import *
like I said above, this should be part of the `_mac_key.py` file
```suggestion
```

2022-07-31 15:56 UTC, Cube707 commented
I am not jet sure if I prefere the "proper" way of having a seperate file for mac, or if I am fine with a dirty override in the `__init__` file (nobody needs a file with only one line...). I will have to sleep on that. leav it as is for now

2022-07-31 16:05 UTC, Cube707 commented
also please rebase to current master, as some stuff changed in 77c1ac5

2022-07-31 16:07 UTC, Cube707 commented
and do you have access to a mac? can you provide screenshot of the `tests/manual-test.py` file not working currently with ENTER but after the fix? That would be great for documentation.

2022-08-02 12:01 UTC, fleytman commented
Now my Mac uses \n, but I remember exactly what didn't work and was saved only by changing to \r. I think now you can close the MP, and if I reproduce there will already be additional data in what situation such a problem appears.

2022-08-02 12:01 UTC, closed without merging

2022-08-02 12:04 UTC, Cube707 commented
OK, thats weird 🤦🏼‍♂️ 
Definitely open a new issue if you can reproduce it 👍🏼

2022-08-02 12:05 UTC, Cube707 commented
you can still open a PR for your refactoring of the `if` statements. Thats a nice idea.